#!/usr/bin/bash

# Garante que as props necessárias estejam presentes
if [ -f /var/lib/waydroid/waydroid_base.prop ]; then
    if ! grep -q "persist.waydroid.udev=true" "/var/lib/waydroid/waydroid_base.prop"; then
        echo "persist.waydroid.udev=true" >> /var/lib/waydroid/waydroid_base.prop
    fi
    if ! grep -q "persist.waydroid.uevent=true" "/var/lib/waydroid/waydroid_base.prop"; then
        echo "persist.waydroid.uevent=true" >> /var/lib/waydroid/waydroid_base.prop
    fi
    sed -i "s/ro.hardware.gralloc=.*/ro.hardware.gralloc=minigbm_gbm_mesa/g" /var/lib/waydroid/waydroid_base.prop
fi

systemctl start waydroid-container.service
